name: Build and deploy ASP.Net Core app to Azure Web App - ziur

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        working-directory: ./src/ZiurSoftware
        run: dotnet restore ZiurSoftware.sln

      - name: Build
        working-directory: ./src/ZiurSoftware
        run: dotnet build ZiurSoftware.sln -c Release --no-restore

      - name: Publish Server
        working-directory: ./src/ZiurSoftware
        run: dotnet publish ZiurSoftware/ZiurSoftware.csproj -c Release --no-build -o "${{ env.DOTNET_ROOT }}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6C7091BF69184C9BB6769F8035839719 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_18B9B14131514829BE1309922593603F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9BFEF4DFEAB94662B254A83603204006 }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ziur
          slot-name: Production
          package: .